title: Bautista Peco
logo: "/images/Bautista-Peco-r.png?raw=true"
description: >
  Gen AI Engineer | CTO at CICLICO | Ex-MercadoLibre
  <br><br>
  As a Data Scientist with a strong foundation in Data Analysis, Business Intelligence, and Machine Learning, I am dedicated to transforming complex challenges into actionable solutions. By combining technical expertise with strategic insights, I strive to revolutionize decision-making processes that drive real-world results.\n\nCurrently, I bring this vision to life as the co-founder of CICLICO, a circular economy startup that reimagines food transportation. Leveraging data-driven innovation, we aim to eliminate single-use packaging by implementing sustainable, reusable systems that deliver measurable environmental and operational impact.
  <br><br>
  <hr>
  <a href="https://www.linkedin.com/in/bautista-peco/">LinkedIn Profile</a> 
